services:
  - type: web
    name: rev-performance-analysis
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: /opt/render/uploads
      - key: PUBLIC_FOLDER
        value: /opt/render/project/src/public
      - key: MAX_CONTENT_LENGTH
        value: "16777216"  # 16MB in bytes
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /opt/render/uploads
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PYTHONUNBUFFERED
        value: "1" 