services:
  - type: web
    name: healthcare-revenue-analyzer
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --workers 2 --threads 2 --timeout 120
    healthCheckPath: /health
    healthCheckTimeout: 300
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /opt/render/uploads
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: UPLOAD_FOLDER
        value: /opt/render/uploads
      - key: PUBLIC_FOLDER
        value: /opt/render/public
      - key: MAX_CONTENT_LENGTH
        value: "16777216"  # 16MB in bytes 